apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strawman-auth-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: strawman-auth-service
    spec:
      containers:
        - name: strawman-auth-service
          image: docker.io/bingxuanying/strawman-auth-service
          ports:
            - containerPort: 8080
