apiVersion: api/v1
kind: Deployment
metadata:
  name: strawman-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strawman-deployment
  template:
    metadata:
      labels:
        app: strawman-deployment
    spec:
      containers:
        - name: strawman-auth-service
          image: bingxuanying/strawman-auth-service:v0.1.2
          ports:
            - containerPort: 8080
              name: http
              resources:
                requests:
                  memory: 64Mi
                  cpu: 250m
                limits:
                  memory: 128Mi
                  cpu: 500m
        - name: strawman-admin-service
          image: bingxuanying/strawman-admin-service:v0.1.2
          ports:
            - containerPort: 8081
              name: http
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
        - name: strawman-data-service
          image: bingxuanying/strawman-data-service:v0.1.1
          ports:
            - containerPort: 8082
              name: http
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: strawman-service
  labels:
    name: strawman-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: strawman-deployment
  type: LoadBalancer
