apiVersion: apps/v1
kind: Deployment
metadata:
  name: strawman-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strawman-deployment
  template:
    metadata:
      labels:
        app: strawman-deployment
    spec:
      containers:
        - name: gateway-service
          image: bingxuanying/strawman-gateway-service:v0.1
          ports:
            - containerPort: 8080
              name: http

        - name: auth-service
          image: bingxuanying/strawman-auth-service:v0.2.6
          ports:
            - containerPort: 8081
              name: http

        - name: admin-service
          image: bingxuanying/strawman-admin-service:v0.2
          ports:
            - containerPort: 8082
              name: http

        - name: data-service
          image: bingxuanying/strawman-data-service:v0.2
          ports:
            - containerPort: 8083
              name: http

        - name: discovery-service
          image: bingxuanying/strawman-discovery-service:v0.1
          ports:
            - containerPort: 8761
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: strawman-service
  labels:
    name: strawman-service
spec:
  type: LoadBalancer
  selector:
    app: strawman-deployment
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
